openapi: 3.0.2
info:
  title: Pyrra
  version: 0.3.4
servers:
- url: /api/v1
paths:
  /objectives:
    get:
      operationId: ListObjectives
      parameters:
      - explode: true
        in: query
        name: expr
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Objectives'
          description: List Objectives
      summary: List Objectives
      tags:
      - objectives
  /objectives/status:
    get:
      operationId: GetObjectiveStatus
      parameters:
      - explode: true
        in: query
        name: expr
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: grouping
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ObjectiveStatus'
                type: array
          description: Get objective status
      summary: Get objective status
      tags:
      - objectives
  /objectives/errorbudget:
    get:
      operationId: GetObjectiveErrorBudget
      parameters:
      - explode: true
        in: query
        name: expr
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: grouping
        required: false
        schema:
          type: string
        style: form
      - description: The timestamp to start the query range at
        explode: true
        in: query
        name: start
        required: false
        schema:
          type: integer
        style: form
      - description: The timestamp to end the query range at
        explode: true
        in: query
        name: end
        required: false
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryRange'
          description: Get ErrorBudget graph sample pairs
      summary: Get ErrorBudget graph sample pairs
      tags:
      - objectives
  /objectives/alerts:
    get:
      operationId: GetMultiBurnrateAlerts
      parameters:
      - explode: true
        in: query
        name: expr
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: grouping
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: inactive
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - explode: true
        in: query
        name: current
        required: false
        schema:
          default: false
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/MultiBurnrateAlert'
                type: array
          description: Get GetMultiBurnrateAlerts for the Objective
      summary: Get the MultiBurnrateAlerts for the Objective
      tags:
      - objectives
  /objectives/red/requests:
    get:
      operationId: GetREDRequests
      parameters:
      - explode: true
        in: query
        name: expr
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: grouping
        required: false
        schema:
          type: string
        style: form
      - description: The timestamp to start the query range at
        explode: true
        in: query
        name: start
        required: false
        schema:
          type: integer
        style: form
      - description: The timestamp to end the query range at
        explode: true
        in: query
        name: end
        required: false
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryRange'
          description: Get a matrix of requests by label
      summary: Get a matrix of requests by label
      tags:
      - objectives
  /objectives/red/errors:
    get:
      operationId: GetREDErrors
      parameters:
      - explode: true
        in: query
        name: expr
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: grouping
        required: false
        schema:
          type: string
        style: form
      - description: The timestamp to start the query range at
        explode: true
        in: query
        name: start
        required: false
        schema:
          type: integer
        style: form
      - description: The timestamp to end the query range at
        explode: true
        in: query
        name: end
        required: false
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryRange'
          description: Get a matrix of error percentage by label
      summary: Get a matrix of error percentage by label
      tags:
      - objectives
components:
  schemas:
    Objectives:
      items:
        $ref: '#/components/schemas/Objective'
      type: array
    Objective:
      example:
        indicator:
          latency:
            total:
              matchers:
              - name: name
                type: 1
                value: value
              - name: name
                type: 1
                value: value
              metric: metric
              name: name
            success:
              matchers:
              - name: name
                type: 1
                value: value
              - name: name
                type: 1
                value: value
              metric: metric
              name: name
            grouping:
            - grouping
            - grouping
          ratio:
            total:
              matchers:
              - name: name
                type: 1
                value: value
              - name: name
                type: 1
                value: value
              metric: metric
              name: name
            grouping:
            - grouping
            - grouping
            errors:
              matchers:
              - name: name
                type: 1
                value: value
              - name: name
                type: 1
                value: value
              metric: metric
              name: name
        description: description
        window: 6
        config: config
        labels:
          key: labels
        target: 0.8008281904610115
      properties:
        labels:
          additionalProperties:
            type: string
          type: object
        description:
          type: string
        target:
          format: double
          type: number
        window:
          format: int64
          type: integer
        config:
          type: string
        indicator:
          $ref: '#/components/schemas/Indicator'
      required:
      - config
      - description
      - labels
      - target
      - window
      type: object
    Indicator:
      example:
        latency:
          total:
            matchers:
            - name: name
              type: 1
              value: value
            - name: name
              type: 1
              value: value
            metric: metric
            name: name
          success:
            matchers:
            - name: name
              type: 1
              value: value
            - name: name
              type: 1
              value: value
            metric: metric
            name: name
          grouping:
          - grouping
          - grouping
        ratio:
          total:
            matchers:
            - name: name
              type: 1
              value: value
            - name: name
              type: 1
              value: value
            metric: metric
            name: name
          grouping:
          - grouping
          - grouping
          errors:
            matchers:
            - name: name
              type: 1
              value: value
            - name: name
              type: 1
              value: value
            metric: metric
            name: name
      properties:
        ratio:
          $ref: '#/components/schemas/Indicator_ratio'
        latency:
          $ref: '#/components/schemas/Indicator_latency'
      type: object
    Query:
      example:
        matchers:
        - name: name
          type: 1
          value: value
        - name: name
          type: 1
          value: value
        metric: metric
        name: name
      properties:
        metric:
          type: string
        name:
          type: string
        matchers:
          items:
            $ref: '#/components/schemas/Query_matchers'
          type: array
      required:
      - metric
      type: object
    ObjectiveStatus:
      example:
        availability:
          total: 6.027456183070403
          percentage: 0.8008281904610115
          errors: 1.4658129805029452
        labels:
          key: labels
        budget:
          total: 5.962133916683182
          max: 2.3021358869347655
          remaining: 5.637376656633329
      properties:
        labels:
          additionalProperties:
            type: string
          type: object
        availability:
          $ref: '#/components/schemas/ObjectiveStatus_availability'
        budget:
          $ref: '#/components/schemas/ObjectiveStatus_budget'
      required:
      - availability
      - budget
      type: object
    MultiBurnrateAlert:
      example:
        severity: severity
        for: 0
        short:
          current: 5.962133916683182
          query: query
          window: 1
        state: inactive
        factor: 6.027456183070403
        long:
          current: 5.962133916683182
          query: query
          window: 1
        labels:
          key: labels
      properties:
        labels:
          additionalProperties:
            type: string
          type: object
        severity:
          type: string
        for:
          format: int64
          type: integer
        factor:
          format: double
          type: number
        short:
          $ref: '#/components/schemas/Burnrate'
        long:
          $ref: '#/components/schemas/Burnrate'
        state:
          enum:
          - inactive
          - pending
          - firing
          type: string
      required:
      - factor
      - for
      - labels
      - long
      - severity
      - short
      - state
      type: object
    Burnrate:
      example:
        current: 5.962133916683182
        query: query
        window: 1
      properties:
        window:
          format: int64
          type: integer
        current:
          format: double
          type: number
        query:
          type: string
      required:
      - current
      - query
      - window
      type: object
    QueryRange:
      example:
        query: query
        values:
        - - 0.8008281904610115
          - 0.8008281904610115
        - - 0.8008281904610115
          - 0.8008281904610115
        labels:
        - labels
        - labels
      properties:
        query:
          type: string
        labels:
          items:
            type: string
          type: array
        values:
          items:
            items:
              format: double
              type: number
            type: array
          type: array
      required:
      - labels
      - query
      - values
      type: object
    Indicator_ratio:
      example:
        total:
          matchers:
          - name: name
            type: 1
            value: value
          - name: name
            type: 1
            value: value
          metric: metric
          name: name
        grouping:
        - grouping
        - grouping
        errors:
          matchers:
          - name: name
            type: 1
            value: value
          - name: name
            type: 1
            value: value
          metric: metric
          name: name
      properties:
        errors:
          $ref: '#/components/schemas/Query'
        total:
          $ref: '#/components/schemas/Query'
        grouping:
          items:
            type: string
          type: array
      required:
      - errors
      - total
      type: object
    Indicator_latency:
      example:
        total:
          matchers:
          - name: name
            type: 1
            value: value
          - name: name
            type: 1
            value: value
          metric: metric
          name: name
        success:
          matchers:
          - name: name
            type: 1
            value: value
          - name: name
            type: 1
            value: value
          metric: metric
          name: name
        grouping:
        - grouping
        - grouping
      properties:
        success:
          $ref: '#/components/schemas/Query'
        total:
          $ref: '#/components/schemas/Query'
        grouping:
          items:
            type: string
          type: array
      required:
      - success
      - total
      type: object
    Query_matchers:
      example:
        name: name
        type: 1
        value: value
      properties:
        name:
          type: string
        value:
          type: string
        type:
          type: integer
      type: object
    ObjectiveStatus_availability:
      example:
        total: 6.027456183070403
        percentage: 0.8008281904610115
        errors: 1.4658129805029452
      properties:
        percentage:
          format: double
          type: number
        total:
          format: double
          type: number
        errors:
          format: double
          type: number
      required:
      - errors
      - percentage
      - total
      type: object
    ObjectiveStatus_budget:
      example:
        total: 5.962133916683182
        max: 2.3021358869347655
        remaining: 5.637376656633329
      properties:
        total:
          format: double
          type: number
        remaining:
          format: double
          type: number
        max:
          format: double
          type: number
      required:
      - max
      - remaining
      - total
      type: object
